const fs = require('fs');
const path = require('path');

const packages = [
  // --- 1. 동남아 (Southeast Asia) ---
  {
    id: 'pkg-sea-01',
    title: '[힐링특가] 베트남 다낭 & 호이안 4박 5일 5성급 리조트 + 바나힐 골든브릿지',
    slug: 'danang-hoian-5d',
    region: '동남아',
    country: '베트남',
    city: '다낭 / 호이안',
    theme: '휴양/힐링',
    durationDays: 5,
    durationNights: 4,
    price: 699000,
    originalPrice: 890000,
    rating: 4.9,
    reviewCount: 128,
    isFeatured: true,
    isEarlyBird: true,
    thumbnail: 'https://images.unsplash.com/photo-1559592413-7cec4d0cae2b?auto=format&fit=crop&w=1000&q=80',
    images: ['https://images.unsplash.com/photo-1559592413-7cec4d0cae2b?auto=format&fit=crop&w=1000&q=80'],
    tags: ['5성급호텔', '전일정식사', '노옵션노쇼핑', '바나힐케이블카', '호이안야경'],
    summary: '다낭 5성급 비치 프론트 리조트 숙박과 호이안 올드타운 투어, 바나힐 골든브릿지까지 알차게 즐기는 베스트셀러 휴양 패키지입니다.',
    highlights: ['전 일정 5성급 인터내셔널 비치 리조트 투숙 & 오션뷰 조식', '유네스코 세계문화유산 호이안 올드타운 야경 투어', '바나힐 테마파크 & 골든브릿지 케이블카 탑승'],
    included: ['왕복 항공권', '5성급 리조트 4박', '전 일정 전용 차량/가이드', '여행자 보험 1억원'],
    excluded: ['가이드/기사 팁($50)', '개인 경비'],
    departureDates: [{ date: '2026-09-05', price: 699000, status: '예약가능', seatsLeft: 8 }]
  },
  {
    id: 'pkg-sea-02',
    title: '[프라이빗 허니문] 발리 우붓 & 울루와투 럭셔리 독채 풀빌라 4박 6일',
    slug: 'bali-luxury-pool-villa-6d',
    region: '동남아',
    country: '인도네시아',
    city: '발리 / 우붓',
    theme: '허니문/럭셔리',
    durationDays: 6,
    durationNights: 4,
    price: 1850000,
    originalPrice: 2200000,
    rating: 4.98,
    reviewCount: 82,
    isFeatured: true,
    isEarlyBird: false,
    thumbnail: 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=1000&q=80',
    images: ['https://images.unsplash.com/photo-1537996194471-e657df975ab4?auto=format&fit=crop&w=1000&q=80'],
    tags: ['독채풀빌라', '단독가이드', '플로팅조식', '울루와투선셋', '스파120분'],
    summary: '둘만의 오붓한 프라이빗 풀빌라, 인스타 감성의 발리 스윙과 플로팅 조식, 울루와투 절벽 선셋 디너를 즐기는 최고급 허니문 플랜입니다.',
    highlights: ['전 일정 5성급 럭셔리 프라이빗 풀빌라', '발리 스윙 & 계단식 논 뷰 카페', '풀빌라 플로팅 브렉퍼스트 & 짐바란 씨푸드 디너'],
    included: ['가루다 항공 직항', '풀빌라 4박', '단독 가이드 & 전용 차량', '고급 스파 120분 2회'],
    excluded: ['인도네시아 도착비자($35)', '가이드 매너팁'],
    departureDates: [{ date: '2026-09-13', price: 1850000, status: '예약가능', seatsLeft: 4 }]
  },
  {
    id: 'pkg-sea-03',
    title: '[미식&야경] 태국 방콕 5성급 호텔 호캉스 + 파타야 요트 세일링 3박 5일',
    slug: 'bangkok-pattaya-5d',
    region: '동남아',
    country: '태국',
    city: '방콕 / 파타야',
    theme: '온천/미식',
    durationDays: 5,
    durationNights: 3,
    price: 580000,
    originalPrice: 750000,
    rating: 4.87,
    reviewCount: 142,
    isFeatured: false,
    isEarlyBird: true,
    thumbnail: 'https://images.unsplash.com/photo-1508009603885-50cf7c579365?auto=format&fit=crop&w=1000&q=80',
    images: ['https://images.unsplash.com/photo-1508009603885-50cf7c579365?auto=format&fit=crop&w=1000&q=80'],
    tags: ['차오프라야디너크루즈', '파타야요트투어', '방콕야시장', '태국전통마사지'],
    summary: '차오프라야 강변 5성급 호텔 숙박, 럭셔리 선셋 요트 크루즈와 미슐랭 빕구르망 방콕 스트리트 푸드를 만끽하는 여행입니다.',
    highlights: ['차오프라야 프린세스 디너 크루즈 탑승', '파타야 프라이빗 요트 세일링 & 스노클링', '태국 왕궁 및 왓 아룬 관람'],
    included: ['왕복 항공권', '5성급 호텔 3박', '전 일정 식사 및 요트 탑승권'],
    excluded: ['가이드 팁 ($40)'],
    departureDates: [{ date: '2026-09-08', price: 580000, status: '예약가능', seatsLeft: 10 }]
  },
  {
    id: 'pkg-sea-04',
    title: '[에메랄드빛 바다] 필리핀 세부 샹그릴라 리조트 + 오슬롭 고래상어 호핑 3박 5일',
    slug: 'cebu-shangrila-5d',
    region: '동남아',
    country: '필리핀',
    city: '세부 / 막탄',
    theme: '휴양/힐링',
    durationDays: 5,
    durationNights: 3,
    price: 720000,
    originalPrice: 920000,
    rating: 4.91,
    reviewCount: 96,
    isFeatured: false,
    isEarlyBird: true,
    thumbnail: 'https://images.unsplash.com/photo-1518509562904-e7ef99cdcc86?auto=format&fit=crop&w=1000&q=80',
    images: ['https://images.unsplash.com/photo-1518509562904-e7ef99cdcc86?auto=format&fit=crop&w=1000&q=80'],
    tags: ['샹그릴라리조트', '오슬롭고래상어', '단독방카호핑', '스톤마사지'],
    summary: '세부 최고의 샹그릴라 리조트 전용 비치 휴양과 신비로운 오슬롭 고래상어 와칭 투어를 함께 즐기는 프리미엄 휴양!',
    highlights: ['샹그릴라 막탄 리조트 오션윙 투숙', '오슬롭 고래상어 스노클링 & 투말록 폭포', '날루수안 & 힐룽뚱안 아일랜드 호핑투어'],
    included: ['왕복 항공권', '리조트 3박', '호핑투어 및 고래상어 투어 입장료'],
    excluded: ['현지 공항세', '가이드팁'],
    departureDates: [{ date: '2026-09-11', price: 720000, status: '예약가능', seatsLeft: 6 }]
  },
  {
    id: 'pkg-sea-05',
    title: '[시티&테마파크] 싱가포르 마리나베이샌즈 & 센토사 유니버셜 스튜디오 3박 5일',
    slug: 'singapore-mbs-5d',
    region: '동남아',
    country: '싱가포르',
    city: '싱가포르 / 센토사',
    theme: '가족/키즈',
    durationDays: 5,
    durationNights: 3,
    price: 1390000,
    originalPrice: 1650000,
    rating: 4.94,
    reviewCount: 115,
    isFeatured: true,
    isEarlyBird: false,
    thumbnail: 'https://images.unsplash.com/photo-1525625293386-3f8f99389edd?auto=format&fit=crop&w=1000&q=80',
    images: ['https://images.unsplash.com/photo-1525625293386-3f8f99389edd?auto=format&fit=crop&w=1000&q=80'],
    tags: ['마리나베이샌즈1박', '유니버셜스튜디오', '가든스바이더베이', '칠리크랩특식'],
    summary: '인피니티 풀의 성지 마리나베이샌즈 1박 투숙과 센토사섬 유니버셜 스튜디오, 가든스바이더베이 슈퍼트리쇼를 즐기는 시티 럭셔리 투어입니다.',
    highlights: ['마리나베이샌즈 호텔 1박 & 루프탑 인피니티 풀 이용권', '유니버셜 스튜디오 싱가포르 1일 자유이용권', '점보 시푸드 칠리크랩 만찬'],
    included: ['국적기 왕복 항공권', '마리나베이샌즈 1박 + 4성급 2박', '주요 관광지 입장권'],
    excluded: ['개인 경비'],
    departureDates: [{ date: '2026-09-17', price: 1390000, status: '예약가능', seatsLeft: 8 }]
  },

  // --- 2. 유럽 (Europe) ---
  {
    id: 'pkg-eu-01',
    title: '[로맨틱 서유럽] 프랑스 & 스위스 & 이탈리아 3국 8박 10일 핵심일주',
    slug: 'europe-france-swiss-italy-10d',
    region: '유럽',
    country: '프랑스 / 스위스 / 이탈리아',
    city: '파리 / 인터라켄 / 로마 / 베니스',
    theme: '역사/문화',
    durationDays: 10,
    durationNights: 8,
    price: 3890000,
    originalPrice: 4350000,
    rating: 4.95,
    reviewCount: 94,
    isFeatured: true,
    isEarlyBird: false,
    thumbnail: 'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=1000&q=80',
    images: ['https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=1000&q=80'],
    tags: ['루브르박물관', '융프라우요흐', '바티칸패스트트랙', 'TGV고속열차'],
    summary: '에펠탑이 빛나는 파리, 알프스의 여왕 융프라우요흐, 천년 역사의 로마와 수상도시 베니스까지 유럽의 정수를 편안하게 만나는 프리미엄 코스입니다.',
    highlights: ['파리 루브르 박물관 전문 도슨트 해설 투어', '스위스 융프라우요흐 산악열차 등정', '로마 바티칸 박물관 패스트트랙 입장'],
    included: ['국적기 직항 항공권', '4성급 호텔 8박', 'TGV 고속열차 1등석', '주요 박물관 입장료'],
    excluded: ['가이드 팁(100유로)', '도시세'],
    departureDates: [{ date: '2026-09-10', price: 3890000, status: '예약가능', seatsLeft: 6 }]
  },
  {
    id: 'pkg-eu-02',
    title: '[알프스 청정 힐링] 스위스 일주 6박 8일 (체르마트 마테호른 + 인터라켄 + 루체른)',
    slug: 'swiss-alps-healing-8d',
    region: '유럽',
    country: '스위스',
    city: '체르마트 / 인터라켄 / 루체른',
    theme: '휴양/힐링',
    durationDays: 8,
    durationNights: 6,
    price: 4250000,
    originalPrice: 4700000,
    rating: 4.97,
    reviewCount: 68,
    isFeatured: true,
    isEarlyBird: true,
    thumbnail: 'https://images.unsplash.com/photo-1530122037265-a5f1f91d3b99?auto=format&fit=crop&w=1000&q=80',
    images: ['https://images.unsplash.com/photo-1530122037265-a5f1f91d3b99?auto=format&fit=crop&w=1000&q=80'],
    tags: ['스위스파스1등석', '마테호른황금호른', '피르스트액티비티', '빙하특급열차'],
    summary: '웅장한 마테호른의 일출, 피르스트 클리프워크, 브리엔츠 호수 유람선과 빙하특급 열차를 타고 만나는 스위스 대자연 힐링 투어입니다.',
    highlights: ['고르너그라트 전망대 마테호른 뷰 감상', '빙하특급(Glacier Express) 파노라마 열차 탑승', '루체른 카펠교 관람'],
    included: ['왕복 직항 항공권', '전 일정 4성급 산악 롯지/호텔', '스위스 트래블 패스 1등석'],
    excluded: ['개인 경비 및 가이드팁'],
    departureDates: [{ date: '2026-09-15', price: 4250000, status: '예약가능', seatsLeft: 4 }]
  },
  {
    id: 'pkg-eu-03',
    title: '[열정과 예술의 나라] 스페인 & 포르투갈 8박 10일 (바르셀로나 + 마드리드 + 리스본)',
    slug: 'spain-portugal-10d',
    region: '유럽',
    country: '스페인 / 포르투갈',
    city: '바르셀로나 / 그라나다 / 리스본',
    theme: '역사/문화',
    durationDays: 10,
    durationNights: 8,
    price: 3390000,
    originalPrice: 3850000,
    rating: 4.91,
    reviewCount: 88,
    isFeatured: false,
    isEarlyBird: true,
    thumbnail: 'https://images.unsplash.com/photo-1583422409516-2895a77efded?auto=format&fit=crop&w=1000&q=80',
    images: ['https://images.unsplash.com/photo-1583422409516-2895a77efded?auto=format&fit=crop&w=1000&q=80'],
    tags: ['가우디사그라다파밀리아', '알함브라궁전', '플라멩코공연', '하몬&빠에야특식'],
    summary: '가우디의 걸작 사그라다 파밀리아 성당, 이슬람 건축의 정수 알함브라 궁전, 정통 플라멩코와 에그타르트 원조를 맛보는 이베리아 반도 완전정복!',
    highlights: ['사그라다 파밀리아 성당 & 구엘 공원 내부 입장', '알함브라 궁전 프라이빗 도슨트 투어', '세비야 정통 플라멩코 관람'],
    included: ['왕복 항공권', '4성급 호텔 8박', '전용 버스/가이드', '현지 특식 5회'],
    excluded: ['기사/가이드팁 (100유로)'],
    departureDates: [{ date: '2026-09-22', price: 3390000, status: '예약가능', seatsLeft: 8 }]
  },
  {
    id: 'pkg-eu-04',
    title: '[동화 속 중세마을] 동유럽 3국 7박 9일 (체코 프라하 + 오스트리아 비엔나/할슈타트 + 헝가리)',
    slug: 'eastern-europe-9d',
    region: '유럽',
    country: '체코 / 오스트리아 / 헝가리',
    city: '프라하 / 할슈타트 / 비엔나 / 부다페스트',
    theme: '역사/문화',
    durationDays: 9,
    durationNights: 7,
    price: 2990000,
    originalPrice: 3450000,
    rating: 4.93,
    reviewCount: 104,
    isFeatured: true,
    isEarlyBird: false,
    thumbnail: 'https://images.unsplash.com/photo-1541849546-216549ae216d?auto=format&fit=crop&w=1000&q=80',
    images: ['https://images.unsplash.com/photo-1541849546-216549ae216d?auto=format&fit=crop&w=1000&q=80'],
    tags: ['프라하야경', '할슈타트호수', '비엔나쉔브룬궁전', '부다페스트다뉴브유람선'],
    summary: '낭만이 흐르는 프라하 카를교, 유네스코 절경 할슈타트 호수마을, 음악의 도시 비엔나와 야경의 끝판왕 부다페스트 다뉴브강 유람선 투어입니다.',
    highlights: ['프라하 블타바강 야간 유람선 및 카를교 산책', '동화 같은 호수마을 할슈타트 자유 관광', '부다페스트 국회의사당 뷰 다뉴브 크루즈'],
    included: ['왕복 직항 항공권', '4성급 호텔 7박', '체코 꼴레뇨 & 슈니첼 특식'],
    excluded: ['가이드 팁(90유로)'],
    departureDates: [{ date: '2026-09-18', price: 2990000, status: '예약가능', seatsLeft: 6 }]
  },

  // --- 3. 일본 / 동아시아 (Japan & East Asia) ---
  {
    id: 'pkg-jp-01',
    title: '[온천 & 미식 힐링] 일본 홋카이도 삿포로 & 오타루 & 노보리베츠 3박 4일',
    slug: 'japan-hokkaido-sapporo-4d',
    region: '일본/동아시아',
    country: '일본',
    city: '삿포로 / 오타루 / 노보리베츠',
    theme: '온천/미식',
    durationDays: 4,
    durationNights: 3,
    price: 890000,
    originalPrice: 1050000,
    rating: 4.88,
    reviewCount: 156,
    isFeatured: true,
    isEarlyBird: true,
    thumbnail: 'https://images.unsplash.com/photo-1542051841857-5f90071e7989?auto=format&fit=crop&w=1000&q=80',
    images: ['https://images.unsplash.com/photo-1542051841857-5f90071e7989?auto=format&fit=crop&w=1000&q=80'],
    tags: ['온천료칸1박', '3대게요리무제한', '오타루운하', '삿포로맥주박물관'],
    summary: '노보리베츠 천연 온천 료칸에서의 극상 힐링, 신선한 홋카이도 3대 게요리 특식, 오타루 오르골당과 삿포로 도심을 즐기는 완벽한 4일 일정입니다.',
    highlights: ['노보리베츠 전통 온천 료칸 1박 & 가이세키 정식 제공', '홋카이도 대표 미식 3대 게요리(대게, 털게, 킹크랩) 무제한', '영화 러브레터 촬영지 오타루 운하'],
    included: ['왕복 항공권 및 유류세', '온천 료칸 1박 + 삿포로 시내 호텔 2박', '전용 버스 및 가이드'],
    excluded: ['개인 여행 경비'],
    departureDates: [{ date: '2026-09-08', price: 890000, status: '예약가능', seatsLeft: 8 }]
  },
  {
    id: 'pkg-jp-02',
    title: '[천년고도 감성] 일본 오사카 & 교토 & 나라 3박 4일 (온천 호텔 + 유니버셜 스튜디오)',
    slug: 'osaka-kyoto-nara-4d',
    region: '일본/동아시아',
    country: '일본',
    city: '오사카 / 교토 / 나라',
    theme: '가족/키즈',
    durationDays: 4,
    durationNights: 3,
    price: 790000,
    originalPrice: 950000,
    rating: 4.89,
    reviewCount: 130,
    isFeatured: false,
    isEarlyBird: true,
    thumbnail: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&w=1000&q=80',
    images: ['https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&w=1000&q=80'],
    tags: ['교토청수사', '아라시야마대나무숲', '사슴공원', '도톤보리미식'],
    summary: '교토 기요미즈데라와 대나무숲의 고즈넉한 풍경, 나라 사슴공원 먹이주기 체험, 오사카 도톤보리 타코야키/라멘 먹방 투어입니다.',
    highlights: ['교토 청수사(기요미즈데라) & 아라시야마 치쿠린 숲길', '나라 사슴공원 & 도다이지 관람', '도톤보리 자유 쇼핑'],
    included: ['왕복 항공권', '시내 4성급 호텔 3박', '전용 차량 & 가이드'],
    excluded: ['개인 경비'],
    departureDates: [{ date: '2026-09-12', price: 790000, status: '예약가능', seatsLeft: 10 }]
  },
  {
    id: 'pkg-jp-03',
    title: '[온천마을 쉼표] 일본 후쿠오카 & 유후인 & 벳부 2박 3일 료칸 힐링',
    slug: 'fukuoka-yufuin-3d',
    region: '일본/동아시아',
    country: '일본',
    city: '후쿠오카 / 유후인 / 벳부',
    theme: '온천/미식',
    durationDays: 3,
    durationNights: 2,
    price: 650000,
    originalPrice: 790000,
    rating: 4.92,
    reviewCount: 168,
    isFeatured: true,
    isEarlyBird: true,
    thumbnail: 'https://images.unsplash.com/photo-1503899036084-c55cdd92da26?auto=format&fit=crop&w=1000&q=80',
    images: ['https://images.unsplash.com/photo-1503899036084-c55cdd92da26?auto=format&fit=crop&w=1000&q=80'],
    tags: ['유후인긴린코호수', '벳부가마도지옥', '료칸노천탕', '하카타돈코츠라멘'],
    summary: '물안개 피어오르는 유후인 긴린코 호수, 벳부 지옥온천 순례, 전통 료칸에서 즐기는 가이세키 정식과 노천온천욕 힐링 여행입니다.',
    highlights: ['유후인 민예품 거리 유노츠보 가도 산책', '벳부 가마도 지옥온천 족욕 및 온천달걀 시식', '후쿠오카 캐널시티 분수쇼'],
    included: ['왕복 항공권', '온천 료칸 1박 + 후쿠오카 호텔 1박', '전 일정 식사'],
    excluded: ['개인 경비'],
    departureDates: [{ date: '2026-09-09', price: 650000, status: '예약가능', seatsLeft: 12 }]
  },
  {
    id: 'pkg-ea-01',
    title: '[미식과 야경의 도시] 대만 타이베이 & 지우펀 & 예류 3박 4일',
    slug: 'taiwan-taipei-4d',
    region: '일본/동아시아',
    country: '대만',
    city: '타이베이 / 지우펀 / 예류',
    theme: '온천/미식',
    durationDays: 4,
    durationNights: 3,
    price: 520000,
    originalPrice: 650000,
    rating: 4.86,
    reviewCount: 112,
    isFeatured: false,
    isEarlyBird: true,
    thumbnail: 'https://images.unsplash.com/photo-1508248467877-aec1b08de376?auto=format&fit=crop&w=1000&q=80',
    images: ['https://images.unsplash.com/photo-1508248467877-aec1b08de376?auto=format&fit=crop&w=1000&q=80'],
    tags: ['센과치히로지우펀', '스펀풍등날리기', '예류여왕머리바위', '딘타이펑딤섬'],
    summary: '홍등이 낭만적인 지우펀, 소원을 담아 날리는 스펀 천등, 딤섬의 본고장 딘타이펑 특식과 스린 야시장 먹방을 즐기는 알찬 일정!',
    highlights: ['예류 지질공원 여왕머리 기암괴석 관람', '스펀 기찻길 천등(풍등) 날리기 체험', '지우펀 아메이차루 홍등 골목 탐방'],
    included: ['왕복 항공권', '4성급 호텔 3박', '딘타이펑 딤섬 코스 특식'],
    excluded: ['가이드 팁 ($40)'],
    departureDates: [{ date: '2026-09-14', price: 520000, status: '예약가능', seatsLeft: 8 }]
  },

  // --- 4. 미주 / 대양주 (Americas & Oceania) ---
  {
    id: 'pkg-am-01',
    title: '[가족 휴양 베스트] 괌 PIC 리조트 올인클루시브 골드카드 4박 5일',
    slug: 'guam-pic-all-inclusive-5d',
    region: '미주/대양주',
    country: '미국',
    city: '괌',
    theme: '가족/키즈',
    durationDays: 5,
    durationNights: 4,
    price: 1120000,
    originalPrice: 1350000,
    rating: 4.85,
    reviewCount: 110,
    isFeatured: false,
    isEarlyBird: true,
    thumbnail: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=1000&q=80',
    images: ['https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=1000&q=80'],
    tags: ['골드카드전식사', '키즈클럽무료', '워터파크무제한', '돌핀크루즈'],
    summary: '70여 가지 액티비티와 워터파크, 전 일정 호텔 뷔페/디너쇼 식사가 포함된 골드카드로 부모님도 아이도 편안한 괌 최고의 가족 휴양 여행!',
    highlights: ['전 일정 전 식사 포함 PIC 골드카드', '키즈클럽 무료 이용 및 전담 클럽메이트 케어', '돌핀 크루즈 & 스노클링 체험'],
    included: ['국적기 왕복 항공권', 'PIC 리조트 4박', '골드카드 전 식사', '공항 픽업 셔틀'],
    excluded: ['가이드 팁($30)'],
    departureDates: [{ date: '2026-09-04', price: 1120000, status: '예약가능', seatsLeft: 6 }]
  },
  {
    id: 'pkg-am-02',
    title: '[태평양의 낙원] 하와이 오아후 5성급 힐튼 하와이안 빌리지 5박 7일',
    slug: 'hawaii-oahu-hilton-7d',
    region: '미주/대양주',
    country: '미국',
    city: '하와이 / 호놀룰루',
    theme: '허니문/럭셔리',
    durationDays: 7,
    durationNights: 5,
    price: 2490000,
    originalPrice: 2890000,
    rating: 4.96,
    reviewCount: 78,
    isFeatured: true,
    isEarlyBird: false,
    thumbnail: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1000&q=80',
    images: ['https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1000&q=80'],
    tags: ['와이키키비치', '오아후섬일주', '다이아몬드헤드', '울프강스테이크'],
    summary: '와이키키 해변 앞 5성급 리조트 숙박, 오아후 동북부 해안 절경 드라이브 투어와 최고급 스테이크하우스 디너를 즐기는 로맨틱 하와이!',
    highlights: ['힐튼 하와이안 빌리지 리조트 5박', '다이아몬드 헤드 & 하나우마 베이 조망', '와이켈레 프리미엄 아울렛 자유 쇼핑'],
    included: ['대한항공/아시아나 직항 항공권', '리조트 5박', '오아후 섬일주 투어'],
    excluded: ['미국 ESTA 비자 발급비', '리조트피(현지 지불)'],
    departureDates: [{ date: '2026-09-20', price: 2490000, status: '예약가능', seatsLeft: 4 }]
  },
  {
    id: 'pkg-am-03',
    title: '[미서부 3대 도시 & 그랜드캐년] LA & 라스베가스 & 샌프란시스코 7박 9일',
    slug: 'usa-west-grand-canyon-9d',
    region: '미주/대양주',
    country: '미국',
    city: '로스앤젤레스 / 라스베가스 / 샌프란시스코',
    theme: '역사/문화',
    durationDays: 9,
    durationNights: 7,
    price: 3690000,
    originalPrice: 4100000,
    rating: 4.93,
    reviewCount: 92,
    isFeatured: true,
    isEarlyBird: false,
    thumbnail: 'https://images.unsplash.com/photo-1506146332389-18140dc7b2fb?auto=format&fit=crop&w=1000&q=80',
    images: ['https://images.unsplash.com/photo-1506146332389-18140dc7b2fb?auto=format&fit=crop&w=1000&q=80'],
    tags: ['그랜드캐년경비행기', '금문교유람선', '라스베가스야경', '할리우드거리'],
    summary: '대자연의 경이 그랜드캐년, 잠들지 않는 도시 라스베가스의 화려한 쇼, 낭만적인 샌프란시스코 금문교를 아우르는 미서부 완전정복 코스입니다.',
    highlights: ['그랜드캐년 국립공원 림 투어', '샌프란시스코 베이 크루즈 & 금문교 횡단', '할리우드 명예의 거리 & 비벌리힐스 투어'],
    included: ['국적기 왕복 항공권', '미국 1급 호텔 7박', '도시 간 전용 대형 버스'],
    excluded: ['기사/가이드팁 ($90)', 'ESTA 비자'],
    departureDates: [{ date: '2026-09-25', price: 3690000, status: '예약가능', seatsLeft: 6 }]
  },
  {
    id: 'pkg-am-04',
    title: '[청정 호주 대자연] 시드니 오페라하우스 + 블루마운틴 + 포트스테판 4박 6일',
    slug: 'australia-sydney-6d',
    region: '미주/대양주',
    country: '호주',
    city: '시드니 / 블루마운틴 / 포트스테판',
    theme: '휴양/힐링',
    durationDays: 6,
    durationNights: 4,
    price: 1980000,
    originalPrice: 2350000,
    rating: 4.9,
    reviewCount: 84,
    isFeatured: false,
    isEarlyBird: true,
    thumbnail: 'https://images.unsplash.com/photo-1506973035872-a4ec16b8e8d9?auto=format&fit=crop&w=1000&q=80',
    images: ['https://images.unsplash.com/photo-1506973035872-a4ec16b8e8d9?auto=format&fit=crop&w=1000&q=80'],
    tags: ['시드니오페라하우스', '블루마운틴케이블카', '사막모래썰매', '야생돌고래크루즈'],
    summary: '세계 3대 미항 시드니 항구 선셋 크루즈, 유네스코 블루마운틴 국립공원과 포트스테판 사막 모래썰매 & 야생 돌고래 투어!',
    highlights: ['시드니 오페라하우스 내부 가이드 투어', '블루마운틴 시닉월드 3종 케이블카 탑승', '포트스테판 4WD 사막 질주 & 샌드보딩'],
    included: ['국적기 직항 왕복 항공권', '4성급 호텔 4박', '시드니 하버 디너 크루즈'],
    excluded: ['호주 ETA 전자비자 신청비', '가이드팁($50)'],
    departureDates: [{ date: '2026-09-19', price: 1980000, status: '예약가능', seatsLeft: 8 }]
  },

  // --- 5. 국내 (Domestic / Korea) ---
  {
    id: 'pkg-kr-01',
    title: '[국내 프리미엄] 제주 환상 힐링 투어 2박 3일 (그랜드 조선 + 흑돼지 특식)',
    slug: 'jeju-healing-luxury-3d',
    region: '국내',
    country: '대한민국',
    city: '제주 / 서귀포',
    theme: '휴양/힐링',
    durationDays: 3,
    durationNights: 2,
    price: 430000,
    originalPrice: 520000,
    rating: 4.92,
    reviewCount: 75,
    isFeatured: false,
    isEarlyBird: true,
    thumbnail: 'https://images.unsplash.com/photo-1548115184-bc6544d06a58?auto=format&fit=crop&w=1000&q=80',
    images: ['https://images.unsplash.com/photo-1548115184-bc6544d06a58?auto=format&fit=crop&w=1000&q=80'],
    tags: ['5성급그랜드조선', '제주흑돼지구이', '우도보트투어', '카멜리아힐'],
    summary: '제주 5성급 그랜드 조선 호텔 숙박, 우도 산호해변 보트 투어와 제주 흑돼지/갈치조림 미식 코스로 꽉 채운 힐링 여행입니다.',
    highlights: ['5성급 그랜드 조선 제주 2박 연박', '에메랄드빛 우도 섬 투어 및 보트 체험', '제주 최고급 흑돼지 연탄구이 한상차림'],
    included: ['대한항공 왕복 항공권', '그랜드 조선 2박', '우등 리무진 버스', '전 일정 식사'],
    excluded: ['개인 경비'],
    departureDates: [{ date: '2026-09-06', price: 430000, status: '예약가능', seatsLeft: 12 }]
  },
  {
    id: 'pkg-kr-02',
    title: '[남해 바다의 낭만] 여수 밤바다 & 순천만 습지 & 통영 케이블카 2박 3일',
    slug: 'yeosu-suncheon-tongyeong-3d',
    region: '국내',
    country: '대한민국',
    city: '여수 / 순천 / 통영',
    theme: '역사/문화',
    durationDays: 3,
    durationNights: 2,
    price: 360000,
    originalPrice: 420000,
    rating: 4.88,
    reviewCount: 64,
    isFeatured: false,
    isEarlyBird: true,
    thumbnail: 'https://images.unsplash.com/photo-1578637387939-43c525550085?auto=format&fit=crop&w=1000&q=80',
    images: ['https://images.unsplash.com/photo-1578637387939-43c525550085?auto=format&fit=crop&w=1000&q=80'],
    tags: ['여수해상케이블카', '순천만국가정원', '통영루지체험', '남해게장백반'],
    summary: '낭만 가득한 여수 밤바다 야경 크루즈, 대한민국 1호 순천만 국가정원, 통영 한려수도 케이블카를 타며 즐기는 남도 힐링 투어입니다.',
    highlights: ['여수 오동도 동백열차 & 해상 케이블카 탑승', '순천만 갈대습지 전망대 탐방', '남도 10첩 반상 꽃게장 정식'],
    included: ['KTX 왕복 열차권', '특급 리조트 2박', '전용 리무진 버스', '전 일정 남도 식사'],
    excluded: ['개인 경비'],
    departureDates: [{ date: '2026-09-11', price: 360000, status: '예약가능', seatsLeft: 14 }]
  },
  {
    id: 'pkg-kr-03',
    title: '[동해 바다 & 커피향] 강릉 안목해변 + 속초 영금정 + 설악산 케이블카 1박 2일',
    slug: 'gangneung-sokcho-2d',
    region: '국내',
    country: '대한민국',
    city: '강릉 / 속초 / 양양',
    theme: '휴양/힐링',
    durationDays: 2,
    durationNights: 1,
    price: 240000,
    originalPrice: 290000,
    rating: 4.85,
    reviewCount: 92,
    isFeatured: false,
    isEarlyBird: true,
    thumbnail: 'https://images.unsplash.com/photo-1517824806704-9040b037703b?auto=format&fit=crop&w=1000&q=80',
    images: ['https://images.unsplash.com/photo-1517824806704-9040b037703b?auto=format&fit=crop&w=1000&q=80'],
    tags: ['설악산권금성케이블카', '안목커피거리', '속초중앙시장닭강정', '정동진선셋'],
    summary: '설악산의 비경 권금성 케이블카, 시원한 동해 바다 안목해변 커피거리, 속초 중앙시장 만석닭강정과 활어회 만찬 코스입니다.',
    highlights: ['설악산 국립공원 권금성 케이블카 왕복 탑승', '강릉 안목 커피거리 오션뷰 카페 타임', '속초 관광수산시장 먹방 투어'],
    included: ['전용 우등 버스', '동해 4성급 오션뷰 호텔 1박', '식사 3회 및 입장료'],
    excluded: ['개인 음료'],
    departureDates: [{ date: '2026-09-05', price: 240000, status: '예약가능', seatsLeft: 18 }]
  },
  {
    id: 'pkg-kr-04',
    title: '[천년의 역사와 야경] 경주 불국사 & 첨성대 & 황리단길 1박 2일 역사 힐링',
    slug: 'gyeongju-history-2d',
    region: '국내',
    country: '대한민국',
    city: '경주 / 포항',
    theme: '역사/문화',
    durationDays: 2,
    durationNights: 1,
    price: 260000,
    originalPrice: 310000,
    rating: 4.9,
    reviewCount: 80,
    isFeatured: false,
    isEarlyBird: true,
    thumbnail: 'images/destinations/gyeongju-bulguksa.jpg',
    images: ['images/destinations/gyeongju-bulguksa.jpg', 'images/destinations/gyeongju-cheomseongdae.jpg', 'images/destinations/gyeongju-hwangridangil.jpg'],
    tags: ['동궁과월지야경', '불국사석굴암', '황리단길한옥카페', '경주떡갈비한정식'],
    summary: '물에 비친 화려한 신라의 밤 동궁과 월지, 유네스코 불국사와 석굴암, 트렌디한 한옥 거리 황리단길을 함께 만나는 역사 문화 코스입니다.',
    highlights: ['동궁과 월지(안압지) & 첨성대 야경 투어', '불국사 & 석굴암 전문 문화해설사 동행', '황리단길 자유 시간 & 떡갈비 정식'],
    included: ['KTX 왕복 열차권', '경주 힐튼/라한 호텔 1박', '전용 리무진 버스'],
    excluded: ['개인 경비'],
    departureDates: [{ date: '2026-09-12', price: 260000, status: '예약가능', seatsLeft: 16 }]
  },
  {
    id: 'pkg-kr-05',
    title: '[요트 & 오션뷰 호캉스] 부산 해운대 엘시티 & 광안리 드론쇼 & 자갈치 미식 2박 3일',
    slug: 'busan-luxury-yacht-3d',
    region: '국내',
    country: '대한민국',
    city: '부산',
    theme: '휴양/힐링',
    durationDays: 3,
    durationNights: 2,
    price: 490000,
    originalPrice: 580000,
    rating: 4.94,
    reviewCount: 118,
    isFeatured: true,
    isEarlyBird: true,
    thumbnail: 'images/destinations/busan-haeundae-lct.jpg',
    images: ['images/destinations/busan-haeundae-lct.jpg', 'images/destinations/busan-gwangalli-yacht.jpg', 'images/destinations/busan-jagalchi-market.jpg'],
    tags: ['해운대엘시티', '광안리요트투어', '자갈치시장회센터', '흰여울문화마을'],
    summary: '해운대 최고급 오션뷰 호텔 투숙, 광안대교 선셋 요트 세일링과 자갈치 시장 싱싱한 활어회, 영도 흰여울마을 감성 산책 코스입니다.',
    highlights: ['해운대 5성급 럭셔리 오션뷰 호텔 2박', '광안리 선셋 프라이빗 요트 투어', '자갈치 시장 제철 모둠회 & 부산 돼지국밥 특식'],
    included: ['KTX 왕복 열차권', '특급 호텔 2박', '요트 탑승권 및 식사 4회'],
    excluded: ['개인 경비'],
    departureDates: [{ date: '2026-09-18', price: 490000, status: '예약가능', seatsLeft: 10 }]
  }
];

const paths = [
  path.join(__dirname, 'data', 'packages.json'),
  path.join('C:', 'Users', 'kks', '.gemini', 'antigravity', 'scratch', 'travel-agency', 'data', 'packages.json')
];

paths.forEach(p => {
  try {
    fs.mkdirSync(path.dirname(p), { recursive: true });
    fs.writeFileSync(p, JSON.stringify(packages, null, 2), 'utf8');
    console.log('Successfully saved packages to', p);
  } catch (err) {
    console.error('Error saving packages to', p, err);
  }
});
