const fs = require('fs');
const path = require('path');

const shopDir = 'd:\\92.SW\\shop';
const publicDir = path.join(shopDir, 'public');
const dataDir = path.join(shopDir, 'data');
const jsDir = path.join(shopDir, 'js');
const cssDir = path.join(shopDir, 'css');

// Ensure directories exist
[shopDir, publicDir, dataDir, jsDir, cssDir, path.join(publicDir, 'js'), path.join(publicDir, 'css')].forEach(d => {
  if (!fs.existsSync(d)) fs.mkdirSync(d, { recursive: true });
});

// 1. Categories Data
const categories = [
  {
    id: "cat-fashion",
    name: "패션 / 의류",
    icon: "shirt",
    badge: "NEW",
    description: "트렌디한 데일리 룩부터 프리미엄 아우터까지",
    image: "https://images.unsplash.com/photo-1490481651871-ab68de25d43d?auto=format&fit=crop&w=600&q=80"
  },
  {
    id: "cat-digital",
    name: "디지털 / 가전",
    icon: "laptop",
    badge: "HOT",
    description: "스마트한 일상을 위한 최신 스마트 디바이스",
    image: "https://images.unsplash.com/photo-1519389950473-47ba0277781c?auto=format&fit=crop&w=600&q=80"
  },
  {
    id: "cat-beauty",
    name: "뷰티 / 케어",
    icon: "sparkles",
    badge: "BEST",
    description: "피부 본연의 건강한 광채를 위한 스킨케어",
    image: "https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&w=600&q=80"
  },
  {
    id: "cat-living",
    name: "리빙 / 인테리어",
    icon: "home",
    badge: "",
    description: "감각적인 홈 스타일링과 프리미엄 리빙 아이템",
    image: "https://images.unsplash.com/photo-1583847268964-b28dc8f51f92?auto=format&fit=crop&w=600&q=80"
  },
  {
    id: "cat-food",
    name: "푸드 / 키친",
    icon: "coffee",
    badge: "SALE",
    description: "장인의 정성이 담긴 프리미엄 디저트와 다이닝",
    image: "https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=600&q=80"
  }
];

// Load Products generated by generate_60_shop_products.js
const productsRaw = fs.readFileSync(path.join(dataDir, 'products.json'), 'utf8').replace(/^\uFEFF/, '');
const products = JSON.parse(productsRaw);

const orders = [
  {
    orderId: "ORD-20260907-8812",
    orderDate: "2026-09-07 09:30:15",
    customerName: "김민준",
    customerPhone: "010-3849-1290",
    customerEmail: "minjun.kim@example.com",
    shippingAddress: "서울특별시 강남구 테헤란로 152 강남파이낸스센터 18층",
    shippingNote: "부재 시 문 앞에 놓아주세요.",
    paymentMethod: "신용카드 (현대카드)",
    totalAmount: 289000,
    shippingFee: 0,
    discountAmount: 10000,
    status: "배송중",
    trackingNumber: "CJ68291039841",
    items: [
      {
        productId: "prod-01",
        name: "프리미엄 캐시미어 블렌드 오버핏 코트",
        option: "오트밀 베이지 / L(105)",
        quantity: 1,
        price: 289000,
        thumbnail: "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&w=800&q=80"
      }
    ]
  }
];

const inquiries = [
  {
    id: "inq-1",
    author: "박*수",
    date: "2026-09-02",
    productId: "prod-01",
    productName: "프리미엄 캐시미어 블렌드 오버핏 코트",
    question: "178cm / 72kg인데 L사이즈 가면 될까요?",
    answer: "고객님 안녕하세요! 고객님의 체형에는 L(105) 사이즈를 착용하시면 자연스러운 세미 오버핏으로 멋스럽게 착용 가능합니다.",
    status: "답변완료",
    answeredAt: "2026-09-02 14:20"
  }
];

// Write pure UTF-8 JSON data
fs.writeFileSync(path.join(dataDir, 'categories.json'), JSON.stringify(categories, null, 2), 'utf8');
fs.writeFileSync(path.join(dataDir, 'products.json'), JSON.stringify(products, null, 2), 'utf8');
fs.writeFileSync(path.join(dataDir, 'orders.json'), JSON.stringify(orders, null, 2), 'utf8');
fs.writeFileSync(path.join(dataDir, 'inquiries.json'), JSON.stringify(inquiries, null, 2), 'utf8');
console.log('Saved pure UTF-8 data files in d:\\92.SW\\shop\\data');

// 2. Build api.js with DEFAULT_PRODUCTS embedded
const apiJsContent = `/**
 * EasyShop REST API Client Module (v7 Pure UTF-8 with Built-in 60 Products & 1200 Reviews)
 */
const DEFAULT_CATEGORIES = ${JSON.stringify(categories, null, 2)};

const DEFAULT_PRODUCTS = ${JSON.stringify(products, null, 2)};

const DEFAULT_ORDERS = ${JSON.stringify(orders, null, 2)};

const DEFAULT_INQUIRIES = ${JSON.stringify(inquiries, null, 2)};

const ShopAPI = {
  BASE_URL: window.location.origin,

  async request(endpoint, options = {}) {
    const defaultHeaders = {
      'Content-Type': 'application/json',
      'Accept': 'application/json'
    };

    // If on GitHub Pages, directly use static fallback / localStorage
    if (window.location.hostname.includes('github.io')) {
      return await this.fallback(endpoint, options);
    }

    try {
      const response = await fetch(\`\${this.BASE_URL}\${endpoint}\`, {
        ...options,
        headers: {
          ...defaultHeaders,
          ...options.headers
        }
      });

      if (!response.ok) {
        throw new Error(\`HTTP \${response.status}\`);
      }

      return await response.json();
    } catch (error) {
      return await this.fallback(endpoint, options);
    }
  },

  async fallback(endpoint, options = {}) {
    try {
      // 1. Categories
      if (endpoint.startsWith('/api/categories')) {
        try {
          const res = await fetch('data/categories.json?_t=' + Date.now());
          if (res.ok) return await res.json();
        } catch {}
        return DEFAULT_CATEGORIES;
      }

      // 2. Products
      if (endpoint.startsWith('/api/products')) {
        let list = [...DEFAULT_PRODUCTS];
        const method = (options.method || 'GET').toUpperCase();
        const urlObj = new URL('http://dummy.com' + endpoint);
        const id = urlObj.searchParams.get('id');

        // Check localStorage custom products
        try {
          const localCustom = localStorage.getItem('easyshop_custom_products');
          if (localCustom) {
            const customs = JSON.parse(localCustom);
            customs.forEach(cp => {
              const idx = list.findIndex(p => p.id === cp.id);
              if (idx >= 0) list[idx] = cp;
              else list.unshift(cp);
            });
          }
        } catch {}

        if (method === 'GET') {
          if (id) {
            const item = list.find(p => p.id === id);
            return item || list[0] || null;
          }

          const category = urlObj.searchParams.get('category');
          const search = (urlObj.searchParams.get('search') || '').toLowerCase();
          const sort = urlObj.searchParams.get('sort');
          const isBest = urlObj.searchParams.get('isBest');
          const isNew = urlObj.searchParams.get('isNew');
          const isSale = urlObj.searchParams.get('isSale');

          let filtered = [...list];
          if (category && category !== '전체') {
            filtered = filtered.filter(p => p.category === category || p.categoryId === category);
          }
          if (search) {
            filtered = filtered.filter(p => (p.name || '').toLowerCase().includes(search) || (p.summary || '').toLowerCase().includes(search));
          }
          if (isBest === 'true') filtered = filtered.filter(p => p.isBest);
          if (isNew === 'true') filtered = filtered.filter(p => p.isNew);
          if (isSale === 'true') filtered = filtered.filter(p => p.isSale);

          if (sort === 'price_asc') filtered.sort((a, b) => a.price - b.price);
          else if (sort === 'price_desc') filtered.sort((a, b) => b.price - a.price);
          else if (sort === 'rating') filtered.sort((a, b) => (b.rating || 5) - (a.rating || 5));
          else if (sort === 'reviews') filtered.sort((a, b) => (b.reviewCount || 0) - (a.reviewCount || 0));

          return filtered;
        }

        if (method === 'POST') {
          const body = JSON.parse(options.body || '{}');
          body.id = 'prod-' + Date.now();
          body.rating = 5.0;
          body.reviewCount = 0;
          body.reviews = [];
          list.unshift(body);
          try {
            const localCustom = JSON.parse(localStorage.getItem('easyshop_custom_products') || '[]');
            localCustom.unshift(body);
            localStorage.setItem('easyshop_custom_products', JSON.stringify(localCustom));
          } catch {}
          return body;
        }

        if (method === 'PUT') {
          const body = JSON.parse(options.body || '{}');
          const idx = list.findIndex(p => p.id === id);
          if (idx >= 0) {
            list[idx] = { ...list[idx], ...body };
            try {
              const localCustom = JSON.parse(localStorage.getItem('easyshop_custom_products') || '[]');
              const cIdx = localCustom.findIndex(p => p.id === id);
              if (cIdx >= 0) localCustom[cIdx] = list[idx];
              else localCustom.unshift(list[idx]);
              localStorage.setItem('easyshop_custom_products', JSON.stringify(localCustom));
            } catch {}
            return list[idx];
          }
        }

        if (method === 'DELETE') {
          list = list.filter(p => p.id !== id);
          try {
            let localCustom = JSON.parse(localStorage.getItem('easyshop_custom_products') || '[]');
            localCustom = localCustom.filter(p => p.id !== id);
            localStorage.setItem('easyshop_custom_products', JSON.stringify(localCustom));
          } catch {}
          return { success: true };
        }

        return list;
      }

      // 3. Orders
      if (endpoint.startsWith('/api/orders')) {
        let orderList = [...DEFAULT_ORDERS];
        try {
          const localOrders = localStorage.getItem('easyshop_orders');
          if (localOrders) orderList = JSON.parse(localOrders);
        } catch {}

        const method = (options.method || 'GET').toUpperCase();
        const urlObj = new URL('http://dummy.com' + endpoint);
        const orderId = urlObj.searchParams.get('orderId');

        if (method === 'GET') {
          if (orderId) {
            const ord = orderList.find(o => o.orderId === orderId);
            return ord || null;
          }
          return orderList;
        }

        if (method === 'POST') {
          const body = JSON.parse(options.body || '{}');
          body.orderId = 'ORD-' + Date.now();
          body.orderDate = new Date().toISOString().replace('T', ' ').slice(0, 19);
          body.status = '결제완료';
          orderList.unshift(body);
          try {
            localStorage.setItem('easyshop_orders', JSON.stringify(orderList));
          } catch {}
          return body;
        }

        return orderList;
      }

      // 4. Inquiries
      if (endpoint.startsWith('/api/inquiries')) {
        return DEFAULT_INQUIRIES;
      }
    } catch (e) {
      console.error('Fallback error:', e);
    }
    return [];
  },

  // Categories
  async getCategories() {
    return await this.request('/api/categories');
  },

  // Products
  async getProducts(params = {}) {
    const query = new URLSearchParams();
    if (params.category && params.category !== '전체') query.append('category', params.category);
    if (params.search) query.append('search', params.search);
    if (params.sort) query.append('sort', params.sort);
    if (params.minPrice) query.append('minPrice', params.minPrice);
    if (params.maxPrice) query.append('maxPrice', params.maxPrice);
    if (params.isBest) query.append('isBest', 'true');
    if (params.isNew) query.append('isNew', 'true');
    if (params.isSale) query.append('isSale', 'true');
    if (params.isFreeShipping) query.append('isFreeShipping', 'true');

    const qs = query.toString() ? '?' + query.toString() : '';
    return await this.request('/api/products' + qs);
  },

  async getProductById(id) {
    return await this.request('/api/products?id=' + encodeURIComponent(id));
  },

  async createProduct(productData) {
    return await this.request('/api/products', {
      method: 'POST',
      body: JSON.stringify(productData)
    });
  },

  async updateProduct(id, productData) {
    return await this.request('/api/products?id=' + encodeURIComponent(id), {
      method: 'PUT',
      body: JSON.stringify(productData)
    });
  },

  async deleteProduct(id) {
    return await this.request('/api/products?id=' + encodeURIComponent(id), {
      method: 'DELETE'
    });
  },

  // Orders
  async getOrders(params = {}) {
    const query = new URLSearchParams();
    if (params.status && params.status !== '전체') query.append('status', params.status);
    if (params.search) query.append('search', params.search);
    const qs = query.toString() ? '?' + query.toString() : '';
    return await this.request('/api/orders' + qs);
  },

  async getOrderById(orderId) {
    return await this.request('/api/orders?orderId=' + encodeURIComponent(orderId));
  },

  async createOrder(orderData) {
    return await this.request('/api/orders', {
      method: 'POST',
      body: JSON.stringify(orderData)
    });
  },

  async updateOrderStatus(orderId, status, trackingNumber = '') {
    return await this.request('/api/orders?orderId=' + encodeURIComponent(orderId), {
      method: 'PUT',
      body: JSON.stringify({ status, trackingNumber })
    });
  },

  // Inquiries
  async getInquiries() {
    return await this.request('/api/inquiries');
  },

  async createInquiry(inquiryData) {
    return await this.request('/api/inquiries', {
      method: 'POST',
      body: JSON.stringify(inquiryData)
    });
  },

  async answerInquiry(id, answer) {
    return await this.request('/api/inquiries?id=' + encodeURIComponent(id), {
      method: 'PUT',
      body: JSON.stringify({ answer, status: '답변완료', answeredAt: new Date().toISOString().replace('T', ' ').substring(0, 16) })
    });
  },

  // Admin Stats
  async getStats() {
    return await this.request('/api/stats');
  }
};
`;

fs.writeFileSync(path.join(jsDir, 'api.js'), apiJsContent, 'utf8');
fs.writeFileSync(path.join(publicDir, 'js', 'api.js'), apiJsContent, 'utf8');
console.log('Saved pure UTF-8 api.js with 60 products embedded!');
